Add SLSA3
rancher/image-build-multus pull request #71
Opened 2024-09-16 19:18 UTC by rafaelbreno

2024-09-17 09:16 UTC, thomasferrandiz approved these changes
LGTM

2024-10-10 19:52 UTC, brooksn requested changes

2024-10-10 19:52 UTC, brooksn commented on Makefile
> +	docker buildx build \
```suggestion
	docker buildx build \
	$(IID_FILE_FLAG) \
```

2024-10-10 19:52 UTC, brooksn commented on Makefile
> +	docker buildx build \
```suggestion
	docker buildx build \
	$(IID_FILE_FLAG) \
```

2024-10-10 20:05 UTC, brooksn commented
push-to-prime is ready to be added, along with the vault secrets.

2024-10-10 21:56 UTC, brooksn approved these changes

2024-10-11 17:51 UTC, merged